version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: nodejs-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql-app
      - MYSQL_USER=root
      - MYSQL_PASS=secret
      - MYSQL_DB=test
    volumes:
      - ../../:/usr/src/app/
    ports:
      - $NODE_PORT:3000
    container_name: nodejs
    restart: always
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=remote
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=test
    container_name: mysql
    ports:
      - $MYSQL_PORT:3306
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - $PHPMYADMIN_PORT:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: phpmyadmin
    restart: always
networks:
  frontend:
  backend: